apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
  namespace: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: 493471005329.dkr.ecr.ap-northeast-2.amazonaws.com/customer_service:v2
        ports:
        - containerPort: 8080