apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
  namespace: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: 493471005329.dkr.ecr.ap-northeast-2.amazonaws.com/order_service:v2
        ports:
        - containerPort: 8080